config/routes.rb
Rails.application.routes.draw do
  root to: "articles#index"
  resources :articles do
    resources :comments
  end
  resources :tags
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings

  # tag_list attribute setter

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end

  # tag_list attribute getter
  def tag_list
    self.tags.collect do | tag |
      tag.name
    end.join(",")
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true
  has_many :taggings
  has_many :articles, through: :taggings

  # def to_s
  #   name
  # end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :warning
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @comments = @article.comments.all
    @comment = @article.comments.new
    @comment.article_id = @article.id
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.comments.each do |com|
      com.destroy
    end
    @article.taggings.each do |t|
      t.destroy
    end
    @article.destroy
    redirect_to articles_path, warning: 'Article successfuly deleted'
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :tag_list)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]
    @comment.save
    redirect_to article_path(@comment.article)
  end

  private

  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comments.html.erb
<% @comments.each do |com| %>

  <div>
    <h3>Comment by: <%= com.author_name %></h3>
    <small>Posted <%= distance_of_time_in_words(com.article.created_at, com.created_at)%></small>
    <p><%= com.body %></p>
  </div>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <p><%= pluralize(@article.errors.count, "error")%> prohibited the article to be edited</p>
    <ul>
      <% @article.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>
  <br>
  <%= f.label :title, 'Title:' %><br>
  <%= f.text_field :title, placeholder: "Type a title for this Article here !"%>
  <br><br>
  <%= f.label :body, 'Content:'%><br>
  <%= f.text_area :body, placeholder: "Type here the content of the article!"%>
  <br><br>
  <%= f.label :tag_list %><br>
  <%= f.text_field :tag_list %>
  <br><br>
  <%= f.submit 'Save changes article' %>
<% end %>

app/views/articles/index.html.erb
<h1>All ARticles</h2>

<ul>
  <% @articles.each do |art| %>
    <li><%= link_to art.title, article_path(art) %> <%= link_to "Delete this article", article_path(art), method: :delete, data: { confirm: "Are you sure you want to delete this article?" } %> </li>
  <% end %>
</ul>

<%= link_to "Create a new article", new_article_path %>

<br><br><br>
<% if flash[:warning] %>
  <p><%= warning %></p>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <p><%= pluralize(@article.errors.count, "error")%> prohibited the article to be added</p>
    <ul>
      <% @article.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>
  <br>
  <%= f.label :title, 'Title:' %><br>
  <%= f.text_field :title, placeholder: "Type a title for this Article here !"%>
  <br><br>
  <%= f.label :body, 'Content:'%><br>
  <%= f.text_area :body, placeholder: "Type here the content of the article!"%>
  <br><br>
  <%= f.label :tag_list %><br>
  <%= f.text_field :tag_list %>
  <br><br>
  <%= f.submit 'Create this article' %>
<% end %>

app/views/articles/show.html.erb
<h1>ARTICLE SHOW</h1>

<h2><%= @article.title %></h2>
<p><%= @article.body %></p>
<br><br>
<p>
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name+", ", tag_path(tag)%>
  <% end %>
</p>
<br><br>
<%= link_to "Edit this article", edit_article_path(@article)%>
<br><br>
<%= link_to "Delete this article", article_path(@article), method: :delete, data: { confirm: "Are you sure you wan to delete this article?" } %>
<br><br><br>
<%= link_to "<< Back to the list of articles", articles_path%>

<br><br><br>
<% if flash[:warning] %>
  <p><%= warning %></p>
<% end %>

<h2><%= pluralize(@article.comments.count, 'Comment')%></h2>
<%= render partial: 'articles/comments'%>
<%= render partial: 'comments/form' %>

app/views/comments/_form.html.erb
<h3>Leave a comment!</h3>

<%= form_for [@article, @comment ] do |f| %>
  <%= f.label :author_name, 'Enter your name here:' %><br>
  <%= f.text_field :author_name %>
  <br><br>
  <%= f.label :body, 'Type your comment here:' %><br>
  <%= f.text_area :body %>
  <br><br>
  <%= f.submit 'Post this comment'%>
<%end%>

app/views/layouts/_header.html.erb
<ul class="nav justify-content-center">
  <li class="nav-item">
    <a class="nav-link text-white" href="#">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" href="#">Articles List</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" href="#">Tags List </a>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <%= yield %>
    <div>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/tags/index.html.erb
<h1>All tags</h1>

<% @tags.each do |tag| %>
  <%= link_to tag.name+', ', tag_path(tag)%>
<% end %>

app/views/tags/show.html.erb
<h1>Tag show</h1>

<ul>
  <% @tag.articles.each do |art| %>
    <li><%= link_to art.title, article_path(art) %></li>
  <% end %>
<ul>
<%= link_to '<< See all tags here!', tags_path %>